name: buildx

on:
  push:
    branches: main
    tags: 'v*'

jobs:
  buildx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Change for main
      id: change_version
      run: if [ "${{ steps.get_version.outputs.VERSION }}" == "main" ]; then echo ::set-output name=VERSION::latest; else echo ::set-output name=VERSION::${{ steps.get_version.outputs.VERSION }}; fi
    - name: Set up qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest
    - name: Docker Login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      if: github.repository == 'iqtlabs/dovesnap' && github.event_name == 'push'

    - name: Build and push platforms
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: |
        cd openvswitch && \
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --push \
          --file Dockerfile \
          -t iqtlabs/openvswitch:v$(grep 'ENV OVS_VERSION' Dockerfile|grep -oE '[0-9\.]+') . && \
        cd .. && \
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --push \
          --file Dockerfile \
          -t iqtlabs/dovesnap:${{ steps.change_version.outputs.VERSION }} .
      if: github.repository == 'iqtlabs/dovesnap' && github.event_name == 'push'
