name: golangci-lint
on: [push, pull_request]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.31

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          args: --disable-all -E whitespace -E asciicheck -E prealloc -E goconst -E scopelint -E dupl -E dogsled -E goconst -E goprintffuncname -E nakedret -E goprintffuncname -E gochecknoinits

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
